server:
   port: 8081

spring:
  application:
    name: goldencashbunny-backend

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

feign:
  okhttp:
    enabled: true