server:
   port: 8090

spring:
  application:
    name: goldencashbunny-backend

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}

feign:
  okhttp:
    enabled: true