server:
   port: 8090

spring:
  application:
    name: goldencashbunny-backend

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://golden_cash_bunny_user:luPyDuzpp5DCoXy4uTHcWqY4Zkrph8cR@dpg-cmlfd1i1hbls73c8un0g-a/golden_cash_bunny

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

api:
  security:
    token:
      secret: ${JWT_SECRET:secret-key}

feign:
  okhttp:
    enabled: true